Repository RonAsis/Wsep202, pull requests merged in 2020-06, with the labels that each got.

#216 Fetaure/add https support
  trading-system-client/TradingSystemWeb/src/app/app.module.ts
  trading-system-client/TradingSystemWeb/src/app/services/http-intercepter-basic-auth.service.ts
  trading-system-client/TradingSystemWeb/src/app/services/http.service.ts
  trading-system-client/TradingSystemWeb/src/app/services/share.service.ts
  trading-system-client/TradingSystemWeb/src/app/services/user.service.ts
  trading-system-server/pom.xml
  trading-system-server/src/main/java/com/wsep202/TradingSystem/config/TradingSystemConfiguration.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/config/httpSecurity/CustomUserDetail.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/config/httpSecurity/CustomUserDetailsService.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/config/httpSecurity/HttpSecurityConfig.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/config/httpSecurity/HttpsConfig.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/factory/FactoryObjects.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/GrantedAuthorityImpl.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystem.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemDao.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/UserSystem.java
  trading-system-server/src/main/resources/application.properties
Labels: code+test

#217 work add/remove Owner
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/Store.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemFacade.java
Labels: code+test

#219 fix user lock when browser close or refrsh
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/logged-in-user.component.ts
Labels: bug

#220 External interface
  trading-system-client/TradingSystemWeb/angular.json
  trading-system-client/TradingSystemWeb/src/app/guest/shopping-cart/purchase-shopping-cart/purchase-shopping-cart.component.html
  trading-system-client/TradingSystemWeb/src/app/guest/shopping-cart/purchase-shopping-cart/purchase-shopping-cart.component.ts
  trading-system-client/TradingSystemWeb/src/app/shared/paymentDetails.model.ts
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/exception/ExternalSystemException.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/ExternalServiceManagement.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/Receipt.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/ShoppingCart.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/Store.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystem.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemFacade.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/purchase/PaymentDetails.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/dto/PaymentDetailsDto.java
  trading-system-server/src/main/java/externals/BGUChargeSystem.java
  trading-system-server/src/main/java/externals/BGUSupplySystem.java
  trading-system-server/src/main/java/externals/ChargeService.java
  trading-system-server/src/main/java/externals/ChargeSystem.java
  trading-system-server/src/main/java/externals/ChargeSystemFactory.java
  trading-system-server/src/main/java/externals/SupplyService.java
  trading-system-server/src/main/java/externals/SupplySystem.java
  trading-system-server/src/main/java/externals/SupplySystemFactory.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/TradingSystemApplicationTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/config/TestConfig.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/ExternalServiceManagementTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/ShoppingCartTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/helprTests/ExternalServiceManagementMock.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/helprTests/SetUpObjects.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/AdministratorServiceTest/ViewStorePurchaseHistoryTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/AdministratorServiceTest/ViewUserPurchaseHistoryTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/BuyerRegisteredServiceTest/LogoutTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/BuyerRegisteredServiceTest/OpenStoreTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/BuyerRegisteredServiceTest/PurchaseShoppingCartBuyerTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/BuyerRegisteredServiceTest/RemoveProductInShoppingBagTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/BuyerRegisteredServiceTest/SaveProductInShoppingBagTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/BuyerRegisteredServiceTest/ViewPurchaseHistoryTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/BuyerRegisteredServiceTest/WatchShoppingCartTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/BuyerRegisteredServiceTest/addProductToShoppingCartTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/BuyerRegisteredServiceTest/changeProductAmountInShoppingBagTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/GuestServiceTest/LoginTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/GuestServiceTest/PurchaseShoppingCartGuestTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/GuestServiceTest/RegisterTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerManagerTest/ViewPurchaseHistoryTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerManagerTest/addEditDiscountTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerManagerTest/addEditPurchasePolicyTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerManagerTest/removeDiscountTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerOwnerServiceTest/AddManagerTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerOwnerServiceTest/AddOwnerTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerOwnerServiceTest/AddPermissionTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerOwnerServiceTest/AddProductTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerOwnerServiceTest/EditProductTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerOwnerServiceTest/RemoveManagerTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerOwnerServiceTest/RemoveProductTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerOwnerServiceTest/ViewPurchaseHistoryTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerOwnerServiceTest/removeOwnerTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/SellerOwnerServiceTest/removePermissionTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/service/user_service/ServiceTestsHelper.java
Labels: code+test

#224 Feature/init files dis pur appr
  trading-system-server/src/main/java/com/wsep202/TradingSystem/AppStartupRunner.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/OwnersAppointee.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/Store.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/dynamic_start_up/ActivityDefinition.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/dynamic_start_up/AddDiscountDefinition.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/dynamic_start_up/AddPolicyPurchaseDefinition.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/dynamic_start_up/ApproveOwnerDefinition.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/dynamic_start_up/Context.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/ExternalServiceManagementTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/initFileTest.java
  trading-system-server/src/test/java/resources/init_files/test.yaml
  trading-system-server/src/test/java/resources/initialFilesTest.yaml
Labels: code+test

#245 Connection to DB lost
  trading-system-client/TradingSystemWeb/src/app/app.module.ts
  trading-system-client/TradingSystemWeb/src/app/guest/shopping-cart/purchase-shopping-cart/purchase-shopping-cart.component.html
  trading-system-client/TradingSystemWeb/src/app/guest/shopping-cart/purchase-shopping-cart/purchase-shopping-cart.component.ts
  trading-system-client/TradingSystemWeb/src/app/services/http-intercepter-basic-auth.service.ts
  trading-system-server/src/main/java/com/wsep202/TradingSystem/config/httpSecurity/HttpsConfig.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemDataBaseDao.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/notification/Publisher.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/web/controllers/handlers/TradingSystemHandlerException.java
  trading-system-server/src/main/resources/application.properties
Labels: code+test

#247 verify validity
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/exception/CompositeOperatorNullException.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/exception/IllegalMinPriceException.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/exception/IllegalPercentageException.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/factory/FactoryObjects.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/discount/ComposedDiscount.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/discount/ConditionalProductDiscount.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/discount/ConditionalStoreDiscount.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/discount/VisibleDiscount.java
Labels: High priority, code+test

#248 Policy gui
  trading-system-client/TradingSystemWeb/angular.json
  trading-system-client/TradingSystemWeb/src/app/app.module.ts
  trading-system-client/TradingSystemWeb/src/app/guest/products/product-detail/product-detail.component.html
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/owned-store-edit.component.html
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/owned-store-edit.component.ts
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/add-edit-policy/add-edit-policy.component.html
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/add-edit-policy/add-edit-policy.component.ts
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/add-policy/add-policy.component.css
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/add-policy/add-policy.component.html
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/add-policy/add-policy.component.spec.ts
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/add-policy/add-policy.component.ts
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/policies/policies.component.css
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/policies/policies.component.html
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/policies/policies.component.spec.ts
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/policies/policies.component.ts
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/policies/product-policy-item/app-policy-item.component.css
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/policies/product-policy-item/app-policy-item.component.html
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/policies/product-policy-item/policy-item.component.spec.ts
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/policies/product-policy-item/policy-item.component.ts
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/policy.component.html
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/policy.component.ts
  trading-system-client/TradingSystemWeb/src/app/services/http.service.ts
  trading-system-client/TradingSystemWeb/src/app/services/share.service.ts
  trading-system-client/TradingSystemWeb/src/app/services/store.service.ts
  trading-system-client/TradingSystemWeb/src/app/shared/countries.model.ts
  trading-system-client/TradingSystemWeb/src/app/shared/policy.model.ts
  trading-system-client/TradingSystemWeb/src/app/shared/product.model.ts
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/mapping/TradingSystemMapper.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/Store.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystem.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemDao.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemDaoImpl.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemDataBaseDao.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemFacade.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/discount/VisibleDiscount.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/ComposedPurchase.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/Day.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/ProductDetailsPolicy.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/Purchase.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/PurchasePolicy.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/PurchaseType.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/ShoppingBagDetailsPolicy.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/SystemDetailsPolicy.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/UserDetailsPolicy.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/dto/ProductDto.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/dto/PurchasePolicyDto.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/service/user_service/SellerManagerService.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/web/controllers/SellerManagerController.java
  trading-system-server/src/main/resources/application.properties
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/StoreTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/ComposedPurchaseTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/ProductDetailsPolicyTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/ShoppingBagDetailsPolicyTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/SystemDetailsPolicyTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/UserDetailsPolicyTest.java
Labels: High priority, code+test

#252 fix bags
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/header-logging-user/header-logging-user.component.html
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/header-logging-user/header-logging-user.component.ts
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemDaoImpl.java
Labels: bug

#253 fix bugs #250 #244 #241
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/policy/add-policy/add-policy.component.ts
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/exception/IllegalProductCostOrAmountException.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/factory/FactoryObjects.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/Product.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemFacade.java
Labels: bug

#255 fix bugs #235 #236 #239
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/Product.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemDaoImpl.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemFacade.java
Labels: bug

#256 fix bugs
  trading-system-client/TradingSystemWeb/src/app/guest/products/product-detail/product-detail.component.html
  trading-system-client/TradingSystemWeb/src/app/guest/products/product-list/product-item/product-item.component.html
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/Store.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystem.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/UserSystem.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/discount/Discount.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/discount/DiscountPolicy.java
Labels: High priority, bug

#257 Bug/fix 3 bugs
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/history-purchase/recipet-element/receipt-element.component.html
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/edit-product/product-edit-item/product-edit-item.component.html
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/edit-product/product-edit-item/product-edit-item.component.ts
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemDataBaseDao.java
Labels: bug

#262 fix bugs
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/ShoppingCart.java
Labels: bug

#288 fix bugs
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/header-logging-user/header-logging-user.component.ts
  trading-system-client/TradingSystemWeb/src/app/logged-in-user/owned-stores/owned-store-edit/edit-product/add-product/add-product.component.ts
  trading-system-client/TradingSystemWeb/src/app/services/share.service.ts
  trading-system-client/TradingSystemWeb/src/app/shared/product.model.ts
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/Product.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/ShoppingCart.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/Store.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystem.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemDataBaseDao.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemFacade.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/UserSystem.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/cashing/TradingSystemCashing.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/discount/ComposedDiscount.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/discount/ConditionalProductDiscount.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/discount/ConditionalStoreDiscount.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/discount/VisibleDiscount.java
  trading-system-server/src/main/resources/application.properties
Labels: bug

#285 Test ksenia
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystem.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemDao.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemDaoImpl.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/UserSystem.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/discount/VisibleDiscount.java
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/Purchase.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/TradingSystemTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/ComposedPurchaseTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/ProductDetailsPolicyTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/ShoppingBagDetailsPolicyTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/SystemDetailsPolicyTest.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/policy_purchase/UserDetailsPolicyTest.java
Labels: code+test

#284 Usertests
  trading-system-server/src/main/java/com/wsep202/TradingSystem/domain/trading_system_management/Store.java
  trading-system-server/src/test/java/com/wsep202/TradingSystem/domain/trading_system_management/UserSystemTest.java
Labels: bug, code+test
